mysql:
    build: mysql/
    stdin_open: true
    tty: true
    volumes_from:
      - mysqldata
    environment:
      - STARTUP_SQL
      - PYDIO_DB_PW
      - MYSQL_PASS

pydiophp56:
    build: php5/
    stdin_open: true
    tty: true
    volumes_from:
      - pydiodata
      - pydiodatastatic
    links:
      - mysql:mysql

nginxpydio:
    image: nginx-pydio/
    stdin_open: true
    tty: true
    volumes_from:
      - pydiodata
      - pydiodatastatic
    links:
      - mysql:mysql
      - pydiophp56:php56
    environment:
      - VIRTUAL_HOST
