nginxproxy:
    build: nginx-proxy/
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx-proxy/ssl/server:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
