pydiodata:
  image: hasufell/pydio-data
  command: echo pydiodata

mysqldata:
  image: hasufell/gentoo-mysql
  command: echo mysqldata

mysql:
    image: hasufell/gentoo-mysql
    volumes_from:
      - mysqldata
    volumes:
      - ./config/mysql/create_pydio_db.sql:/create_pydio_db.sql
    environment:
      - STARTUP_SQL=/create_pydio_db.sql

php56:
    image: hasufell/gentoo-php5.6
    volumes_from:
      - pydiodata
    volumes:
      - ./config/php5:/etc/php/fpm-php5.6/
    links:
      - mysql:mysql

nginxpydio:
    image: hasufell/gentoo-nginx
    volumes_from:
      - pydiodata
    volumes:
      - ./config/nginx-pydio:/etc/nginx/
    links:
      - mysql:mysql
      - php56:php56

nginxreverse:
    image: hasufell/gentoo-nginx
    volumes:
      - ./config/nginx-reverse:/etc/nginx/
      - ./config/ssl/certs:/etc/ssl/certs/
    links:
        - nginxpydio:nginxpydio
    ports:
      - "80:80"
      - "443:443"

