pydiodata:
  image: hasufell/pydio-data
  command: echo pydiodata

mysqldata:
  image: hasufell/gentoo-mysql
  command: echo mysqldata

mysql:
    image: hasufell/gentoo-mysql
    volumes_from:
      - mysqldata
    volumes:
      - ./config/mysql/create_pydio_db.sql:/create_pydio_db.sql
    environment:
      - STARTUP_SQL=/create_pydio_db.sql

pydiophp56:
    build: php56/
    volumes_from:
      - pydiodata
    volumes:
      - ./config/php5/ext-active:/etc/php/fpm-php5.6/ext-active
      - ./config/php5/fpm.d:/etc/php/fpm-php5.6/fpm.d
    links:
      - mysql:mysql

nginxpydio:
    image: hasufell/gentoo-nginx
    volumes_from:
      - pydiodata
    volumes:
      - ./config/nginx-pydio:/etc/nginx/
      - ./config/ssl/server:/etc/nginx/certs/
    links:
      - mysql:mysql
      - pydiophp56:php56
    environment:
      - VIRTUAL_HOST
