pydiodata:
    image: hasufell/pydio-data:latest
    container_name: pydiodata
    command: echo pydiodata

mysqldata:
    image: hasufell/gentoo-mysql:latest
    container_name: mysqldata
    command: echo mysqldata
    volumes:
      - /var/lib/mysql

