mysql:
    image: hasufell/gentoo-mysql:latest
    stdin_open: true
    tty: true
    volumes_from:
      - mysqldata
      - mysqlconfig
    environment:
      - STARTUP_SQL=/mysql-scripts/create_pydio_db.sql

pydiophp56:
    image: hasufell/gentoo-pydio-php:latest
    stdin_open: true
    tty: true
    volumes_from:
      - pydiodata
      - php5config
    links:
      - mysql:mysql

nginxpydio:
    image: hasufell/gentoo-nginx:latest
    stdin_open: true
    tty: true
    volumes_from:
      - pydiodata
      - nginxconfig
    links:
      - mysql:mysql
      - pydiophp56:php56
    environment:
      - VIRTUAL_HOST
